"""add_deleted_at_to_tickets

Revision ID: ea4acaa99877
Revises: 4de3ae5ae62d
Create Date: 2026-02-18 15:53:16.372494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4acaa99877'
down_revision: Union[str, None] = '4de3ae5ae62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deleted_at')
    # ### end Alembic commands ###
